
services:
  mysql:
    image: mariadb:10.6.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db_data:/var/lib/mysql
    networks: 
      wordpress:
        ipv4_address: 172.20.0.20
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-megapassword}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_ROOT_HOST="%"

  wordpress:
    depends_on: ["mysql"]
    image: wordpress:php8.2-apache
    volumes:
      - wp_data:/var/www/html
    networks: 
      wordpress:
        ipv4_address: 172.20.0.10
    ports: 
     - 8080:80
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD:-password}
      - WORDPRESS_DB_HOST=mysql


networks:
  wordpress:
    driver: bridge
    ipam:
     config:
       - subnet: "172.20.0.0/24"
         gateway: "172.20.0.1"
